services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - file-server
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 --threads 4 "app.web:create_app()"
    volumes:
      - /Users/antonio/Desktop/DataScience/MyCode/langchainX:/chat_pdf/langchainX # Temporary fix
      - ./migrations:/chat_pdf/migrations
      - vector_store:/chat_pdf/vector_store
      - shared_tmp:/tmp
    environment:
      - APP_ENV=production
      - FLASK_APP=wsgi.py
      - UPLOAD_URL=http://nginx/files
      - DOWNLOAD_URL=http://localhost/files
      - PYTHONPATH=/chat_pdf:/chat_pdf/langchainX:${PYTHONPATH}
    networks:
      - app_network
    expose:
      - "8000"
    ports:
      - "8000"
    depends_on:
      - redis
      - postgres
      - file-server

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery.worker.celery_app worker --concurrency=2 --loglevel=INFO
    volumes:
      - /Users/antonio/Desktop/DataScience/MyCode/langchainX:/chat_pdf/langchainX # Temporary fix
      - vector_store:/chat_pdf/vector_store
      - shared_tmp:/tmp
    environment:
      - APP_ENV=production
      - FLASK_APP=wsgi.py
      - UPLOAD_URL=http://nginx/files
      - DOWNLOAD_URL=http://localhost/files
      - PYTHONPATH=/chat_pdf:/chat_pdf/langchainX:${PYTHONPATH}
    networks:
      - app_network
    depends_on:
      - redis
      - postgres
      - file-server

  file-server:
    build:
      context: ../local-do-files
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8050 --workers 2 --threads 2 "app:app"
    volumes:
      - file_uploads:/file_server/uploads
      - shared_tmp:/tmp
    networks:
      - app_network
    expose:
      - "8050"
    ports:
      - "8050" 
    environment:
      - PYTHONPATH=/file-server:$PYTHONPATH
    depends_on:
      - redis
   
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - app_network

volumes:
  redis_data:
  postgres_data:
  file_uploads:
  vector_store:
  shared_tmp:
      driver: local

networks:
  app_network:
    driver: bridge