
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - file_server
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 --threads 4 "app.web:create_app()"
    volumes:
      - /Users/antonio/Desktop/DataScience/MyCode/langchainX:/chat_pdf/langchainX
      - shared_tmp:/tmp
    environment:
      - APP_ENV=production
      - PYTHONPATH=/chat_pdf:/chat_pdf/langchainX:${PYTHONPATH}
    networks:
      - app_network
    expose:
      - "8000"
    ports:
      - "8000"
    depends_on:
      - redis
      - file_server
      - worker

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery.worker.celery_app worker --concurrency=2 --loglevel=INFO
    volumes:
      - /Users/antonio/Desktop/DataScience/MyCode/langchainX:/chat_pdf/langchainX
      - shared_tmp:/tmp
    environment:
      - APP_ENV=production
      - PYTHONPATH=/chat_pdf:/chat_pdf/langchainX:${PYTHONPATH}
    networks:
      - app_network
    depends_on:
      - redis
      - file_server

  file_server:
    build:
      context: ../local-do-files
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8050 --workers 2 --threads 2 "app:app"
    volumes:
      - ../local-do-files:/file_server
      - shared_tmp:/tmp
    networks:
      - app_network
    expose:
      - "8050"
    ports:
      - "8050" 
    environment:
      - PYTHONPATH=/file_server:$PYTHONPATH
    depends_on:
      - redis
   

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

volumes:
  redis_data:
  shared_tmp:
      driver: local

networks:
  app_network:
    driver: bridge