chain:
  condense_question_llm:
    chat_name: OpenAI
    model_name: gpt-4

llm:
  - name: gpt-4o
    builder: build_llm
    module: app.chat.llms.chat_model
    params:
      chat_name: OpenAI
      model_name: gpt-4o

  - name: gpt-4o-mini
    builder: build_llm
    module: app.chat.llms.chat_model
    params:
      chat_name: OpenAI
      model_name: gpt-4o-mini

  # - name: chat-bison
  #   builder: build_llm
  #   module: app.chat.llms.chat_model
  #   # shell:
  #   #   - gcloud auth login
  #   params:
  #     chat_name: VertexAI
  #     model_name: chat-bison

memory:
  - name: buffer_memory
    builder: buffer_memory_builder
    module: app.chat.memories.buffer_memory

  - name: window_memory_3
    builder: window_buffer_memory_builder
    module: app.chat.memories.window_memory
    params:
      k: 3

  - name: window_memory_5
    builder: window_buffer_memory_builder
    module: app.chat.memories.window_memory
    params:
      k: 5

  - name: window_memory_7
    builder: window_buffer_memory_builder
    module: app.chat.memories.window_memory
    params:
      k: 7

  - name: summary_memory_1000
    builder: summary_buffer_memory_builder
    module: app.chat.memories.summary_memory
    params:
      max_token_limit: 1000

  - name: summary_memory_2000
    builder: summary_buffer_memory_builder
    module: app.chat.memories.summary_memory
    params:
      max_token_limit: 2000

  - name: summary_memory_3000
    builder: summary_buffer_memory_builder
    module: app.chat.memories.summary_memory
    params:
      max_token_limit: 3000

embedding:
  - name: openai_small
    model: OpenAI
    params:
      model_name: text-embedding-3-small

  - name: openai_large
    model: OpenAI
    params:
      model_name: text-embedding-3-large

  # - name: microsoft
  #   model: E5

vector_store:
  - name: chroma
    builder: chroma_vector_store_builder
    module: app.chat.vector_stores.chroma

  # - name: pinecone
  #   builder: pinecone_vector_store_builder
  #   module: app.chat.vector_stores.pinecone
    # env:
    #   ENV_VAR: "value"

  # - name: singlestore
  #   builder: singlestore_vector_store_builder
  #   module: app.chat.vector_stores.singlestore

retriever:
  - name: chroma_small
    builder: chroma_retriever_builder
    module: app.chat.vector_stores.chroma
    params:
      embedding_name: openai_small
      search_kwargs:
        k: 3

  - name: chroma_large
    builder: chroma_retriever_builder
    module: app.chat.vector_stores.chroma
    params:
      embedding_name: openai_large
      search_kwargs:
        k: 3


  # - name: pinecone_1
  #   builder: pinecone_retriever_builder
  #   module: app.chat.vector_stores.pinecone
  #   params:
  #     embedding_name: openai
  #     search_kwargs:
  #       k: 1

  # - name: pinecone_2
  #   builder: pinecone_retriever_builder
  #   module: app.chat.vector_stores.pinecone
  #   params:
  #     embedding_name: microsoft
  #     search_kwargs:
  #       k: 2

  # - name: pinecone_3
  #   builder: pinecone_retriever_builder
  #   module: app.chat.vector_stores.pinecone
  #   params:
  #     embedding_name: openai
  #     search_kwargs:
  #       k: 3

  # - name: singlestore_1
  #   builder: singlestore_retriever_builder
  #   module: app.chat.vector_stores.singlestore
  #   params:
  #     embedding_name: openai
  #     search_kwargs:
  #       k: 1

  # - name: singlestore_2
  #   builder: singlestore_retriever_builder
  #   module: app.chat.vector_stores.singlestore
  #   params:
  #     embedding_name: microsoft
  #     search_kwargs:
  #       k: 2

  # - name: singlestore_3
  #   builder: singlestore_retriever_builder
  #   module: app.chat.vector_stores.singlestore
  #   params:
  #     embedding_name: openai
  #     search_kwargs:
  #       k: 3

